import { mysqlTable, char, varchar, tinyint, datetime, date, decimal, text } from "drizzle-orm/mysql-core";

export const patients = mysqlTable("patients", {
  id: char("id", { length: 36 }).primaryKey(),
  patNumber: varchar("pat_number", { length: 30 }),
  salutation: varchar("salutation", { length: 20 }),
  firstName: varchar("first_name", { length: 100 }),
  lastName: varchar("last_name", { length: 100 }),
  sex: varchar("sex", { length: 10 }),
  birthdate: date("birthdate"),
  bloodGrp: varchar("blood_grp", { length: 5 }),
  fatherName: varchar("father_name", { length: 100 }),
  phoneMobile: varchar("phone_mobile", { length: 25 }),
  mobileVerified: tinyint("mobile_verified").default(0),
  phoneHome: varchar("phone_home", { length: 25 }),
  phoneWork: varchar("phone_work", { length: 25 }),
  emailAddress: varchar("email_address", { length: 100 }),
  street: varchar("street", { length: 255 }),
  city: varchar("city", { length: 100 }),
  district: varchar("district", { length: 100 }),
  state: varchar("state", { length: 100 }),
  postalCode: varchar("postalcode", { length: 20 }),
  country: varchar("country", { length: 100 }),
  patientGroupId: char("patient_group_id", { length: 36 }),
  patientcategoryId: char("patientcategory_id", { length: 36 }),
  occupationlistId: char("occupationlist_id", { length: 36 }),
  vipPatient: tinyint("vip_patient").default(0),
  vipDescription: text("vip_description"),
  refralId: char("refral_id", { length: 36 }),
  insprovIderId: char("insprovider_id", { length: 36 }),
  parentId: char("parent_id", { length: 36 }),
  parentType: varchar("parent_type", { length: 100 }),
  relationType: varchar("relation_type", { length: 50 }),
  membershipType: varchar("membership_type", { length: 50 }),
  membershipExpiryDate: date("membership_expiry_date"),
  validTill: date("valid_till"),
  regDiscount: decimal("reg_discount", { precision: 10, scale: 2 }),
  otherDiscount: decimal("other_discount", { precision: 10, scale: 2 }),
  generateBill: tinyint("generate_bill").default(1),
  outstandingAmt: decimal("outstanding_amt", { precision: 12, scale: 2 }),
  regDate: date("reg_date"),
  status: varchar("status", { length: 25 }),
  deleted: tinyint("deleted").default(0),
  createdBy: char("created_by", { length: 36 }),
  modifiedUserId: char("modified_user_id", { length: 36 }),
  assignedUserId: char("assigned_user_id", { length: 36 }),
  dateEntered: datetime("date_entered"),
  dateModified: datetime("date_modified"),
});

export const patientimages = mysqlTable("patientimages", {
  id: char("id", { length: 36 }).primaryKey(),
  patientId: char("patient_id", { length: 36 }),
  imageUrl: varchar("image_url", { length: 500 }),
  imageType: varchar("image_type", { length: 50 }),
  deleted: tinyint("deleted").default(0),
});
